Updates calculator so that it is initated with the list of process ra…
ITVolt/WorkTime pull request #1
Opened 2022-07-24 16:55 UTC by ITBoar

…ther that queries settings file. Adds work time calculator that supports break time

2022-07-25 11:05 UTC, ITVolt reviewed
Finns en del att titta på, det alvarligaste imo är:
1. Att man inte kan ändra processer under runtime längre.
2. Att man måste jobba en timma innan nästa rast, oavsett hur lång rast man angett att man vill ha.

2022-07-25 11:05 UTC, ITVolt commented on Analysis/WorkTimeCalculator.cs
> +            return workProcesses.Contains(focusChange.ProcessName);
Med denna ändring så kan man inte längre ändra/lägga till processer under runtime, vilket jag ser som ett krav då mitt workflow hittills har varit "oh, denna räknas inte men den borde det, jag lägger till den". Man skall inte behöva starta om applikationen och tappa sin nuvarande tid för att ändra en inställning.

Antingen får vi:
1. Återställa och läsa inställningar dynamiskt.
2. Hooka in sig på när inställningar ändras (antingen automatiskt med någon sorts lyssnare, eller ha en "refresh"-knapp) och då om-initialisera Calculatorn med de nya inställningarna

2022-07-25 11:05 UTC, ITVolt commented on Analysis/WorkWithBreakCalculator.cs
> +        public WorkWithBreakCalculator(IEnumerable<string> workProcesses, TimeSpan breakTimeAllowed, TimeSpan workTimeBeforeBreak)
Är inte denna klass bara en duplicerad WorkTimeCalculator om man sätter `breakTimeAllowed` till 0?
Känns inte som att man bör ta bort den gamla eller wrappa och använda sig av dess logik även i denna klass.

2022-07-25 11:05 UTC, ITVolt commented on Analysis/WorkWithBreakCalculator.cs
> +        private bool ProcessCountAsWork(FocusChangedLogEntry focusChange)
Givet namnet så skall denna metod inte ta in ett focusChange utan en process/processnamn (samma gäller för icke-break-caculator).

2022-07-25 11:05 UTC, ITVolt commented on Analysis/WorkWithBreakCalculator.cs
> +    internal class WorkWithBreakCalculator : TimeCalculator
Finns ingen visuell indikation på att tid tickar som rast. En enkel ändring skulle vara att ändra return-boolen `isCurrentlyWorking` till ett enum med typ `Working`, `OnBreak`, `Idle/NotWorking` och tex sätta bakgrunden till en blå nyans ifall man är `OnBreak`.

2022-07-25 11:05 UTC, ITVolt commented on Analysis/WorkWithBreakCalculator.cs
> +        private static (TimeSpan remainingBreakTime, TimeSpan allowedBreakTime) CalculateBreakTime(TimeSpan breakSpan, TimeSpan currentBreakTime)
Namnen här gör mig mycket förvirrad. `breakSpan` borde snarare vara `requestedBreakTime` och `currentBreakTime` borde vara `remainingBreakTime`.

Sen känns metoden i sig lite weird, hade nog varit smidigare att dumma ner den lite och bara fråga "hur mycket rast får jag". Och då känns den överflödig och man kan då skippa den helt. Dvs att man kan skriva om dess användning (nuvarande rad 51-53) till typ:
```cs
var allowedBreakTime = Math.Max(currentBreakTime - duration, TimeSpan.Zero); // currentBreakTime borde döpas om som jag nämnde tidigare.
cumulativeWorkTime += allowedBreakTime;
currentBreakTime -= allowedBreakTime;
```

2022-07-25 11:05 UTC, ITVolt commented on Analysis/WorkWithBreakCalculator.cs
> +            var currentWorkToBreak = this.workTimeBeforeBreak;
`this.workTimeBeforeBreak` känns överflödig nu tycker jag. Den skulle bara behövas ifall man skulle vilja ändra hur lång tid som behövs innan man får ta rast. Men den är ändå readonly idag och KAN inte ändras. Dessutom heter den nya inställningen i appsettings `NrbOfMinutesBreakPerHour` så om man skulle ange något annat än 60 min skulle det bli väldigt konstigt.

Tror man gör saker mer lättläst/lättanvänt idag ifall vi inte tar in detta i konstruktorn utan helt enkelt har det statiskt till 60 min.

2022-07-25 11:05 UTC, ITVolt commented on Analysis/WorkWithBreakCalculator.cs
> +                    if (duration >= currentWorkToBreak)
Denna logik känns sketchy.

Den baseras på att du måste jobba 60 min och sen "refreshas" din rast. Exempelvis om man knappat in att man vill ha 10 min rast per timma och tar max rast så måste man: Jobb 60 min => rast 10 min => jobb 60 min => rast 10 min = 140 min.
Vilket visar att rasten räknas inte in i "timman" utan man måste faktiskt JOBBA en timma för att förnya rasten. Ta exemplet med 30 minuter rast per timma. Detta borde betyda att du behöver "jobba" totalt 4 timmar för att få ihop en hel 8 timmars arbetsdag ifall du utnyttjar raster optimalt. Men med denna logiken måste du faktiskt jobba 5.5 timmar.

Detta _kanske_ löser sig ifall man helt enkelt initialiserar/förnyar tiden till `60 min - breakTimeAllowed`, dvs att med 5 min rast så behöver du jobba 55 min innan den förnyas. Har dock inte tänkt igenom det helt så det kan finnas issues med det.

2022-07-25 11:25 UTC, ITBoar commented on Analysis/WorkTimeCalculator.cs
> +            return workProcesses.Contains(focusChange.ProcessName);
Det känns vettigt att återställa till dynamisk i så fall i nuläget. Känns som mer prio att kunna ändra i processer i gränssnittet än att bygga upp en uppdatering flöde för settings filen.

2022-07-25 11:27 UTC, ITBoar commented on Analysis/WorkWithBreakCalculator.cs
> +        public WorkWithBreakCalculator(IEnumerable<string> workProcesses, TimeSpan breakTimeAllowed, TimeSpan workTimeBeforeBreak)
Lite så och jag tror jag tar en extra vända för att se om jag kan prova en wrapper/decorater lösning. Har en viss preferens för att separera de för att slippa hanteringen av breaks i worktime versionen.

2022-07-25 11:28 UTC, ITBoar commented on Analysis/WorkWithBreakCalculator.cs
> +        private bool ProcessCountAsWork(FocusChangedLogEntry focusChange)
Det är bra fångat ska korrigera.

2022-07-25 11:32 UTC, ITBoar commented on Analysis/WorkWithBreakCalculator.cs
> +    internal class WorkWithBreakCalculator : TimeCalculator
Funderade ursprungligen till att ha det som en extra grej efter att ha lagt till break kalkylator. Men att köra på en enum lösning tror jag kan bli en bra lösning så fixar det med. Blir ju lite kul att prova om jag kommer på nått fint sätt att indikerar mer än färg för att öka accessability faktorn.

2022-07-25 11:33 UTC, ITBoar commented on Analysis/WorkWithBreakCalculator.cs
> +        private static (TimeSpan remainingBreakTime, TimeSpan allowedBreakTime) CalculateBreakTime(TimeSpan breakSpan, TimeSpan currentBreakTime)
Bra fångat. Borde nog tänkt till en extra gång på att få in max uttrycket som förenklar allt.

2022-07-31 21:11 UTC, ITVolt requested changes
Tycker det är bra överlag, men "Counters" och "Process" kan tjäna på en fundering på deras namn och/eller innehåll :)

2022-07-31 21:11 UTC, ITVolt commented on Analysis/Counters/Counter.cs
> +    public abstract void AddProcess(Process process);
Diz be weird.
1. "Counters" som koncept känns konstigt. En räknare borde räkna upp något, det den gör nu är att öka tiden akumulativt. Dvs att det snarare är ett stoppur, klocka eller timer.
2. En "Process"-klass väntar jag mig innehålla information om en process, kanske till och med actions för att påverka den.
Men den håller typ ingen info om processen förutom "IsWork" (vilket argumenterbart inte egentligen har med processen att göra heller) och en "Duration" vilket absolut känns ännu konstigare att ha på en "Process".
Gissar på ett bättre namn för "Process" skulle snarare vara "SomethingEntry" eller "FocusChange".

2022-08-01 13:54 UTC, ITBoar commented on Analysis/Counters/Counter.cs
> +    public abstract void AddProcess(Process process);
1. Tänker jag provar timer i att det defineras ibland som ".. or device that measures or records the amount of time taken by a process or activity." 
Är lite rädd att det kan bli missförstånd i att man tror att man ska sätta x tid och att den sen ska räknar ner, men tror det blir bäst av förslagen och av vad jag kan komma på.

2. FocusEntry i så fall :) med ändringar till IsWork => IsOnWork. Alternativt så skulle man kunna säga focusIntervall, focusTime, focusSpan eller bara focus om du tror det blir bättre.
FocusChange finns i viss mån redan i delen av programmet när man lyssnar på ändringarna så är inte så övertygad om den.

2022-08-01 21:23 UTC, merged